
const GET_PRODUCTS_START = 'GET_PRODUCTS_START';
const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR';
const TOGGLE_LOADING = 'TOGGLE_LOADING';
const SET_PRODUCT_DETAILS = 'SET_PRODUCT_DETAILS';

export default {
  GET_PRODUCTS_START,
  GET_PRODUCTS_SUCCESS,
  GET_PRODUCTS_ERROR,
  TOGGLE_LOADING,
  SET_PRODUCT_DETAILS,
};
