
const GET_PRODUCTS_START = 'GET_PRODUCTS_START';
const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR';
const SET_PRODUCT_DETAILS = 'SET_PRODUCT_DETAILS';
const SET_PRODUCTS_ON_CART = 'SET_PRODUCTS_ON_CART';
const UPDATE_PRODUCTS_ON_CART = 'UPDATE_PRODUCTS_ON_CART';
const SET_SEARCH = 'SET_SEARCH';
const SET_ORDER = 'SET_ORDER';
const FINALIZE_PURCHASE = 'FINALIZE_PURCHASE';
const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';

export default {
  GET_PRODUCTS_START,
  GET_PRODUCTS_SUCCESS,
  GET_PRODUCTS_ERROR,
  SET_PRODUCT_DETAILS,
  SET_PRODUCTS_ON_CART,
  UPDATE_PRODUCTS_ON_CART,
  SET_SEARCH,
  SET_ORDER,
  FINALIZE_PURCHASE,
  SET_CURRENT_PAGE,
};
